# -*- coding: utf-8 -*-
"""Swin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZl-WrLYPFV-b4NU1YQcigo7UUDvev6b

# Swin Transformer - base and adversarial configurations
This notebook runs base (non-adversarial) and AutoAttack versions of the Swin Transformer on two datasets: the NIH Chest X-ray classification dataset and the ISIC Skin Cancer classification dataset.
"""

# Installations & mount Drive
!pip install timm==0.4.12 yacs==0.1.8 adversarial-robustness-toolbox
!pip install -U PyYAML
!pip install git+https://github.com/fra31/auto-attack
from google.colab import drive
drive.mount('/content/drive')

# remove hidden ipynb checkpoints and .DS_Store from data folders to avoid later FileNotFoundError
!rm -R /content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic/isic_org/.ipynb_checkpoints
!rm -R /content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic/isic_org/.DS_Store

"""Run Swin Transformer configurations

NIH Chest X-ray dataset
"""

# Commented out IPython magic to ensure Python compatibility.
# # Run base swin transformer on clean chest x-ray dataset
# %%bash
# #python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345  /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/main.py --cfg /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --resume /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/swin_tiny_patch4_window7_224.pth --data-path /content/drive/MyDrive/MLSP_Masters/ECE_697/data/imagenet --batch-size 128 --output /content/drive/MyDrive/MLSP_Masters/ECE_697/data/swin_chxray_base_output --use-checkpoint
# # Evaluate base swin transformer on noisy chest x-ray dataset (after 40 epochs of clean training)
# python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345  /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/main.py --cfg /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --resume /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/ckpt_epoch_150.pth --data-path /content/drive/MyDrive/MLSP_Masters/ECE_697/data/imagenet --batch-size 128 --output /content/drive/MyDrive/MLSP_Masters/ECE_697/data/swin_chxray_base_output --use-checkpoint
#

# Run adversarial swin transformer on chest x-ray dataset
!pip install git+https://github.com/fra31/auto-attack
!python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/swin_autoattack.py --cfg=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --data_dir=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/swin_auto_1000 --csv=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/swin_autoattack_1000.csv --model=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/ckpt_epoch_150.pth --save_dir=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/swin_chxray_adv_outputs/results --batch_size=128 --num_workers=1 --log_path=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/swin_chxray_adv_outputs 
#!python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345 ~/Models/Swin-Transformer/swin_autoattack.py --cfg=configs/swin/swin_tiny_patch4_window7_224.yaml --data_dir=~/Data/chxray/raw_imgs --data_path=~/Data/chxray/imagenet --csv=~/Data/chxray/autoattack_labels.csv --model=ckpt_epoch_150.pth --save_dir=~/Models/swin_chxray_adv_output/results --batch_size=128 --num_workers=1 --log_path=~/Models/swin_chxray_adv_outputs/results/logger.txt

"""ISIC Dataset"""

# Run base swin transformer on clean ISIC dataset
#!python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345  /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/main.py --cfg /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --resume /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/swin_tiny_patch4_window7_224.pth --data-path /content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic/isic_org --batch-size 128 --opts TRAIN.EPOCHS 200 TRAIN.WARMUP_EPOCHS 10 TRAIN.BASE_LR 0.0002 --output /content/drive/MyDrive/MLSP_Masters/ECE_697/data/swin_isic_base_output #--use-checkpoint
# Evaluate base swin transformer on noisy ISIC dataset (after 40 epochs of clean training)
!python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345  /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/main.py --cfg /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --resume /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/isic_ckpt_epoch_40.pth --data-path /content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic/isic_org --batch-size 128 --opts TRAIN.EPOCHS 200 TRAIN.WARMUP_EPOCHS 10 TRAIN.BASE_LR 0.0002 --output /content/drive/MyDrive/MLSP_Masters/ECE_697/data/swin_isic_base_output #--use-checkpoint

while True:
  print(1)

# Run adversarial swin transformer on ISIC dataset

!python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/swin_autoattack.py --cfg=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --data_dir=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_1000 --csv=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_1000.csv --model=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/isic_ckpt_epoch_150.pth --save_dir=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/swin_isic_adv_outputs/results --batch_size=224 --num_workers=1 --log_path=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/swin_isic_adv_outputs --csv_tr=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_train.csv --csv_ts=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_test.csv

!python /content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/swin_autoattack.py --cfg=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/configs/swin/swin_tiny_patch4_window7_224.yaml --data_dir=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_1000 --csv=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_1000.csv --model=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/Swin-Transformer/isic_ckpt_epoch_150.pth --save_dir=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/swin_isic_adv_outputs/results --batch_size=224 --num_workers=1 --log_path=/content/drive/MyDrive/MLSP_Masters/ECE_697/models/swin_isic_adv_outputs --csv_tr=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_train.csv --csv_ts=/content/drive/MyDrive/MLSP_Masters/ECE_697/data/isic_auto_test.csv

